const menu=document.querySelector('.menu'),links=document.querySelector('.mobile-links');menu.addEventListener('click',()=>{const open=menu.getAttribute('aria-expanded')==='true';menu.setAttribute('aria-expanded',String(!open));links.hidden=open;menu.textContent=open?'Menu':'Close'});links.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{links.hidden=true;menu.setAttribute('aria-expanded','false');menu.textContent='Menu'}));const dialog=document.querySelector('#pricing');document.querySelector('#pricing-open').addEventListener('click',()=>dialog.showModal());dialog.querySelector('.close').addEventListener('click',()=>dialog.close());dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close()}});const video=document.querySelector('.hero video');if(matchMedia('(prefers-reduced-motion: reduce)').matches){video.autoplay=false;video.pause();}

const inquiry=document.querySelector('#inquiry-form'),phone=inquiry.elements.phone,dateInput=inquiry.elements.date,statusNote=document.querySelector('#form-status');
const dateParts=new Intl.DateTimeFormat('en-US',{timeZone:'America/Chicago',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date());
const part=t=>dateParts.find(p=>p.type===t).value;dateInput.min=`${part('year')}-${part('month')}-${part('day')}`;
phone.addEventListener('input',()=>phone.setCustomValidity(''));
function selectPackage(value){document.querySelector('#selected-package').value=value;const choice=document.querySelector('#package-choice');choice.hidden=false;choice.textContent=`Your choice: ${value}`;}
document.querySelectorAll('.package-select').forEach(a=>a.addEventListener('click',()=>selectPackage(a.dataset.package)));
inquiry.addEventListener('submit',async event=>{event.preventDefault();const digits=phone.value.replace(/\D/g,'');phone.setCustomValidity(/^(?:1)?\d{10}$/.test(digits)?'':'Please enter a valid 10-digit US phone number.');if(!inquiry.reportValidity())return;if(inquiry.elements._honey.value)return;const button=inquiry.querySelector('button[type="submit"]'),data=new FormData(inquiry);data.append('_subject',`AACT Booths wedding inquiry — ${data.get('eventType')} — ${data.get('date')}`);data.append('_template','table');data.append('_captcha','false');data.set('eventType','Wedding');data.append('source','AACT wedding website');button.disabled=true;button.textContent='Sending your request…';statusNote.className='form-note full-width';statusNote.textContent='Sending your event details…';try{const response=await fetch('https://formsubmit.co/ajax/allaroundchitown@gmail.com',{method:'POST',headers:{Accept:'application/json'},body:data});const result=await response.json();if(!response.ok||!(result.success===true||result.success==='true'))throw new Error('Request not accepted');statusNote.textContent='Thanks! Your inquiry was sent. We’ll contact you to confirm availability and pricing. Your date is not reserved yet.';statusNote.classList.add('success');inquiry.reset();document.querySelector('#package-choice').hidden=true;}catch(error){statusNote.textContent='We couldn’t send your request. Your details are still here. Please try again or call/text (224) 234-1473.';statusNote.classList.add('error');}finally{button.disabled=false;button.textContent='Check availability & get pricing';}});
